#pragma once

// Split Keeb Stuff

#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_TX_PIN GP8
#define SERIAL_USART_RX_PIN GP9

#define MASTER_LEFT

#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_OLED_ENABLE
#define SPLIT_LED_STATE_ENABLE
#define SPLIT_POINTING_ENABLE


// Bootmagic 
#define BOOTMAGIC_ROW 0
#define BOOTMAGIC_COLUMN 6

//Joystick 
#define ANALOG_JOYSTICK_X_AXIS_PIN GP28
#define ANALOG_JOYSTICK_Y_AXIS_PIN GP29
#define ANALOG_JOYSTICK_AXIS_MIN 0
#define ANALOG_JOYSTICK_AXIS_MAX 1023
#define ANALOG_JOYSTICK_SPEED_REGULATOR 40
#define ANALOG_JOYSTICK_READ_INTERVAL 10
#define ANALOG_JOYSTICK_SPEED_MAX 2

#define POINTING_DEVICE_LEFT
#define POINTING_DEVICE_INVERT_X
//#define POINTING_DEVICE_AUTO_MOUSE_ENABLE   
//#define AUTO_MOUSE_DEFAULT_LAYER <0>

//TODO: OLEDS
#define I2C_DRIVER I2CD1
#define I2C1_SCL_PIN GP27
#define I2C1_SDA_PIN GP26